//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryAndData.DataContext
{

    public partial class Pet
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
