//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryAndData.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetsContext : DbContext
    {
        public PetsContext(): base("name=PetsContext")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
    }
}
